ruleset:
  type: object
  properties:
    name:
      type: string
    base_attributes_config:
      type: object
      properties:
        total_time_attribute_code:
          type: string
          default: combat_total_time
        speed_attribute_code:
          type: string
          default: player_speed
        draw_count_attribute_code:
          type: string
          default: player_draw_count
        hand_up_limit_attribute_code:
          type: string
          default: player_hand_up_limit
    victory_conditions:
      description: victory if the one of conditions has been matched
      type: array
      items:
        type: object
        properties:
          on:
            type: string
            enum:
              - timeout
              - playing
          target:
            type: object
            properties:
              range:
                type: string
                enum:
                  - all
                  - any
              side:
                type: string
                enum:
                  - myself
                  - enemies
                  - friends
                  - others
                  - all
          conditions:
            description: should match all of conditions
            type: array
            items:
              type: object
              properties:
                attribute_code:
                  type: string
                operator_func:
                  $ref: 'common/enum.yaml#/operator_func_enum'
                value:
                  type: integer


attributes_init:
  combat_attributes:
    description: attribute_code => integer
    type: object
    additionalProperties:
      type: integer
  player_attributes:
    description: attribute_code => integer
    type: object
    additionalProperties:
      type: integer
